### PR TITLE
Update for modern platformio

### PR DESCRIPTION
**Pull request by ellensp**
### Description

Currently this code will not build on modern versions of platformio and python

Updated python code to work
Updated deprecated platformio keywords

### Benefits

Builds under current platformio

### CODE REVIEW

**Comment by ellensp** [comment]
@Sovol3d  please review and merge

**Comment by Sveeeeeen** [comment]
+1

**Comment by ellensp** [comment]
@Sovol3d please review and merge

**Comment by Sveeeeeen** [comment]
@Sovol3d please review and merge

**Comment by ellensp** [comment]
Ok, it is very apparent that Sovol 3D does not care about their customers in the slightest.

**Pull request closed without merging**
